@echo off
setlocal enabledelayedexpansion

set "ROOT=%~dp0.."
for %%I in ("%ROOT%") do set "ROOT=%%~fI"

echo Building all release packages...
echo.

REM ------------------------------------------------------------------
REM Windows x86_64
REM ------------------------------------------------------------------
echo [1/8] Windows x86_64...
call "%~dp0package-windows.bat"
if errorlevel 1 (
  echo ERROR: Windows package build failed
  exit /b 1
)

REM ------------------------------------------------------------------
REM Unix packages — each via a SINGLE-LINE PowerShell command (no ^ continuations)
REM ------------------------------------------------------------------

set "ROOT2=%ROOT:\=\\%"

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root='%ROOT2%'; $dist=$root+'\dist'; $target='frankenphp-linux-x86_64'; $source=$root+'\'+$target; if(-not (Test-Path $source)){Write-Warning('Source not found: '+$source);exit 0}; $pkg=$target.Substring(11); $build=$dist+'\.build-tmp\pencarimovie-downloader-'+$pkg; Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path ($build+'\bin')|Out-Null; foreach($f in @('backend.php','index.php','router.php','composer.json','composer.lock','composer.phar','install.sh','install-termux.sh','start.sh','start-termux.sh','restart.sh','restart-termux.sh','stop.sh','package.json','LICENSE','THIRD_PARTY_NOTICES.md','SECURITY.md')){$src=$root+'\'+$f;if(Test-Path $src){Copy-Item -Force $src $build}}; Copy-Item -Recurse -Force ($root+'\public') ($build+'\public'); New-Item -ItemType Directory -Force -Path ($build+'\storage')|Out-Null; Copy-Item -Force ($root+'\storage\.gitkeep') ($build+'\storage\.gitkeep') -ErrorAction SilentlyContinue; Copy-Item -Force ($root+'\bin\php.ini.unix') ($build+'\bin\php.ini'); Copy-Item -Force ($root+'\bin\php') ($build+'\bin\php'); Copy-Item -Force $source ($build+'\bin\frankenphp'); if(Test-Path ($root+'\vendor\autoload.php')){Copy-Item -Recurse -Force ($root+'\vendor') ($build+'\vendor')}; $tarPath=$dist+'\pencarimovie-downloader-'+$pkg+'.tar.gz'; if(Test-Path $tarPath){Remove-Item -Force $tarPath}; tar -czf $tarPath -C $build .; Write-Host ('  [2/8] Created '+$tarPath)"
if errorlevel 1 echo ERROR: frankenphp-linux-x86_64 failed

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root='%ROOT2%'; $dist=$root+'\dist'; $target='frankenphp-linux-x86_64-gnu'; $source=$root+'\'+$target; if(-not (Test-Path $source)){Write-Warning('Source not found: '+$source);exit 0}; $pkg=$target.Substring(11); $build=$dist+'\.build-tmp\pencarimovie-downloader-'+$pkg; Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path ($build+'\bin')|Out-Null; foreach($f in @('backend.php','index.php','router.php','composer.json','composer.lock','composer.phar','install.sh','install-termux.sh','start.sh','start-termux.sh','restart.sh','restart-termux.sh','stop.sh','package.json','LICENSE','THIRD_PARTY_NOTICES.md','SECURITY.md')){$src=$root+'\'+$f;if(Test-Path $src){Copy-Item -Force $src $build}}; Copy-Item -Recurse -Force ($root+'\public') ($build+'\public'); New-Item -ItemType Directory -Force -Path ($build+'\storage')|Out-Null; Copy-Item -Force ($root+'\storage\.gitkeep') ($build+'\storage\.gitkeep') -ErrorAction SilentlyContinue; Copy-Item -Force ($root+'\bin\php.ini.unix') ($build+'\bin\php.ini'); Copy-Item -Force ($root+'\bin\php') ($build+'\bin\php'); Copy-Item -Force $source ($build+'\bin\frankenphp'); if(Test-Path ($root+'\vendor\autoload.php')){Copy-Item -Recurse -Force ($root+'\vendor') ($build+'\vendor')}; $tarPath=$dist+'\pencarimovie-downloader-'+$pkg+'.tar.gz'; if(Test-Path $tarPath){Remove-Item -Force $tarPath}; tar -czf $tarPath -C $build .; Write-Host ('  [3/8] Created '+$tarPath)"
if errorlevel 1 echo ERROR: frankenphp-linux-x86_64-gnu failed

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root='%ROOT2%'; $dist=$root+'\dist'; $target='frankenphp-linux-x86_64-mimalloc'; $source=$root+'\'+$target; if(-not (Test-Path $source)){Write-Warning('Source not found: '+$source);exit 0}; $pkg=$target.Substring(11); $build=$dist+'\.build-tmp\pencarimovie-downloader-'+$pkg; Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path ($build+'\bin')|Out-Null; foreach($f in @('backend.php','index.php','router.php','composer.json','composer.lock','composer.phar','install.sh','install-termux.sh','start.sh','start-termux.sh','restart.sh','restart-termux.sh','stop.sh','package.json','LICENSE','THIRD_PARTY_NOTICES.md','SECURITY.md')){$src=$root+'\'+$f;if(Test-Path $src){Copy-Item -Force $src $build}}; Copy-Item -Recurse -Force ($root+'\public') ($build+'\public'); New-Item -ItemType Directory -Force -Path ($build+'\storage')|Out-Null; Copy-Item -Force ($root+'\storage\.gitkeep') ($build+'\storage\.gitkeep') -ErrorAction SilentlyContinue; Copy-Item -Force ($root+'\bin\php.ini.unix') ($build+'\bin\php.ini'); Copy-Item -Force ($root+'\bin\php') ($build+'\bin\php'); Copy-Item -Force $source ($build+'\bin\frankenphp'); if(Test-Path ($root+'\vendor\autoload.php')){Copy-Item -Recurse -Force ($root+'\vendor') ($build+'\vendor')}; $tarPath=$dist+'\pencarimovie-downloader-'+$pkg+'.tar.gz'; if(Test-Path $tarPath){Remove-Item -Force $tarPath}; tar -czf $tarPath -C $build .; Write-Host ('  [4/8] Created '+$tarPath)"
if errorlevel 1 echo ERROR: frankenphp-linux-x86_64-mimalloc failed

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root='%ROOT2%'; $dist=$root+'\dist'; $target='frankenphp-linux-aarch64'; $source=$root+'\'+$target; if(-not (Test-Path $source)){Write-Warning('Source not found: '+$source);exit 0}; $pkg=$target.Substring(11); $build=$dist+'\.build-tmp\pencarimovie-downloader-'+$pkg; Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path ($build+'\bin')|Out-Null; foreach($f in @('backend.php','index.php','router.php','composer.json','composer.lock','composer.phar','install.sh','install-termux.sh','start.sh','start-termux.sh','restart.sh','restart-termux.sh','stop.sh','package.json','LICENSE','THIRD_PARTY_NOTICES.md','SECURITY.md')){$src=$root+'\'+$f;if(Test-Path $src){Copy-Item -Force $src $build}}; Copy-Item -Recurse -Force ($root+'\public') ($build+'\public'); New-Item -ItemType Directory -Force -Path ($build+'\storage')|Out-Null; Copy-Item -Force ($root+'\storage\.gitkeep') ($build+'\storage\.gitkeep') -ErrorAction SilentlyContinue; Copy-Item -Force ($root+'\bin\php.ini.unix') ($build+'\bin\php.ini'); Copy-Item -Force ($root+'\bin\php') ($build+'\bin\php'); Copy-Item -Force $source ($build+'\bin\frankenphp'); if(Test-Path ($root+'\vendor\autoload.php')){Copy-Item -Recurse -Force ($root+'\vendor') ($build+'\vendor')}; $tarPath=$dist+'\pencarimovie-downloader-'+$pkg+'.tar.gz'; if(Test-Path $tarPath){Remove-Item -Force $tarPath}; tar -czf $tarPath -C $build .; Write-Host ('  [5/8] Created '+$tarPath)"
if errorlevel 1 echo ERROR: frankenphp-linux-aarch64 failed

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root='%ROOT2%'; $dist=$root+'\dist'; $target='frankenphp-linux-aarch64-gnu'; $source=$root+'\'+$target; if(-not (Test-Path $source)){Write-Warning('Source not found: '+$source);exit 0}; $pkg=$target.Substring(11); $build=$dist+'\.build-tmp\pencarimovie-downloader-'+$pkg; Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path ($build+'\bin')|Out-Null; foreach($f in @('backend.php','index.php','router.php','composer.json','composer.lock','composer.phar','install.sh','install-termux.sh','start.sh','start-termux.sh','restart.sh','restart-termux.sh','stop.sh','package.json','LICENSE','THIRD_PARTY_NOTICES.md','SECURITY.md')){$src=$root+'\'+$f;if(Test-Path $src){Copy-Item -Force $src $build}}; Copy-Item -Recurse -Force ($root+'\public') ($build+'\public'); New-Item -ItemType Directory -Force -Path ($build+'\storage')|Out-Null; Copy-Item -Force ($root+'\storage\.gitkeep') ($build+'\storage\.gitkeep') -ErrorAction SilentlyContinue; Copy-Item -Force ($root+'\bin\php.ini.unix') ($build+'\bin\php.ini'); Copy-Item -Force ($root+'\bin\php') ($build+'\bin\php'); Copy-Item -Force $source ($build+'\bin\frankenphp'); if(Test-Path ($root+'\vendor\autoload.php')){Copy-Item -Recurse -Force ($root+'\vendor') ($build+'\vendor')}; $tarPath=$dist+'\pencarimovie-downloader-'+$pkg+'.tar.gz'; if(Test-Path $tarPath){Remove-Item -Force $tarPath}; tar -czf $tarPath -C $build .; Write-Host ('  [6/8] Created '+$tarPath)"
if errorlevel 1 echo ERROR: frankenphp-linux-aarch64-gnu failed

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root='%ROOT2%'; $dist=$root+'\dist'; $target='frankenphp-mac-arm64'; $source=$root+'\'+$target; if(-not (Test-Path $source)){Write-Warning('Source not found: '+$source);exit 0}; $pkg=$target.Substring(11); $build=$dist+'\.build-tmp\pencarimovie-downloader-'+$pkg; Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path ($build+'\bin')|Out-Null; foreach($f in @('backend.php','index.php','router.php','composer.json','composer.lock','composer.phar','install.sh','install-termux.sh','start.sh','start-termux.sh','restart.sh','restart-termux.sh','stop.sh','package.json','LICENSE','THIRD_PARTY_NOTICES.md','SECURITY.md')){$src=$root+'\'+$f;if(Test-Path $src){Copy-Item -Force $src $build}}; Copy-Item -Recurse -Force ($root+'\public') ($build+'\public'); New-Item -ItemType Directory -Force -Path ($build+'\storage')|Out-Null; Copy-Item -Force ($root+'\storage\.gitkeep') ($build+'\storage\.gitkeep') -ErrorAction SilentlyContinue; Copy-Item -Force ($root+'\bin\php.ini.unix') ($build+'\bin\php.ini'); Copy-Item -Force ($root+'\bin\php') ($build+'\bin\php'); Copy-Item -Force $source ($build+'\bin\frankenphp'); if(Test-Path ($root+'\vendor\autoload.php')){Copy-Item -Recurse -Force ($root+'\vendor') ($build+'\vendor')}; $tarPath=$dist+'\pencarimovie-downloader-'+$pkg+'.tar.gz'; if(Test-Path $tarPath){Remove-Item -Force $tarPath}; tar -czf $tarPath -C $build .; Write-Host ('  [7/8] Created '+$tarPath)"
if errorlevel 1 echo ERROR: frankenphp-mac-arm64 failed

powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; $root='%ROOT2%'; $dist=$root+'\dist'; $target='frankenphp-mac-x86_64'; $source=$root+'\'+$target; if(-not (Test-Path $source)){Write-Warning('Source not found: '+$source);exit 0}; $pkg=$target.Substring(11); $build=$dist+'\.build-tmp\pencarimovie-downloader-'+$pkg; Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path ($build+'\bin')|Out-Null; foreach($f in @('backend.php','index.php','router.php','composer.json','composer.lock','composer.phar','install.sh','install-termux.sh','start.sh','start-termux.sh','restart.sh','restart-termux.sh','stop.sh','package.json','LICENSE','THIRD_PARTY_NOTICES.md','SECURITY.md')){$src=$root+'\'+$f;if(Test-Path $src){Copy-Item -Force $src $build}}; Copy-Item -Recurse -Force ($root+'\public') ($build+'\public'); New-Item -ItemType Directory -Force -Path ($build+'\storage')|Out-Null; Copy-Item -Force ($root+'\storage\.gitkeep') ($build+'\storage\.gitkeep') -ErrorAction SilentlyContinue; Copy-Item -Force ($root+'\bin\php.ini.unix') ($build+'\bin\php.ini'); Copy-Item -Force ($root+'\bin\php') ($build+'\bin\php'); Copy-Item -Force $source ($build+'\bin\frankenphp'); if(Test-Path ($root+'\vendor\autoload.php')){Copy-Item -Recurse -Force ($root+'\vendor') ($build+'\vendor')}; $tarPath=$dist+'\pencarimovie-downloader-'+$pkg+'.tar.gz'; if(Test-Path $tarPath){Remove-Item -Force $tarPath}; tar -czf $tarPath -C $build .; Write-Host ('  [8/8] Created '+$tarPath)"
if errorlevel 1 echo ERROR: frankenphp-mac-x86_64 failed

REM Clean build tmp
if exist "%ROOT%\dist\.build-tmp" rmdir /s /q "%ROOT%\dist\.build-tmp"

echo.
echo Done. Archives are in "%ROOT%\dist"
exit /b 0
